# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


resources:
  containers:
    - container: rust_container
      image: rust:latest

pool:
  vmImage: 'Ubuntu 16.04'

container: rust_container

steps:
- script: |
    cargo run
  displayName: 'cargo run'
